version: '2'
services:
   elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0
     environment:
       - "xpack.security.enabled=false"
     ports:
       - "9200:9200"

   pio:
     build: pio-container
     depends_on:
       - elasticsearch
     volumes:
       - $PWD/pio-container/conf/pio-env.sh:/pio/PredictionIO-0.11.0-incubating/conf/pio-env.sh
       - $PWD/spark:/pio/spark
     environment:
       - "SPARK_HOME=/pio/spark"
       
     ports:
       - "7070:7070"
         
